### ISSUE TITLE
MQTT->ST command high latency

### ISSUE THREAD

**Issue by jonfink** [stjohnjohnson/smartthings-mqtt-bridge#118]
I've had MQTT bridging my Home Assistant server with my SmartThings Hub (v2) for over a year now. It has always been more or less rock solid (though sometimes delays on the order of a few seconds were annoying). 

Today I thought the entire system stopped working - however after removing/updating/reinstalling the components (ST MQTT Device, MQTT SmartApp, smartthings-mqtt-bridge server, mosquitto broker), I think it is working but with VERY long delays from the time a switch is activated in home assistant.

I've traced that everything from Home Assistant -> MQTT -> smartthings-mqtt-bridge server happen very quickly (including the HTTP post to the ST hub) but then things slow down. I see an event pop up in my ST IDE about a minute later and then the actual device switches a minute or two after that....

Realize that this might be a ST problem and nothing to do with the MQTT bridge but thought someone here might have an idea of what could cause this... or how to debug. Any thoughts?

**Comment by Eluminite** [comment]
Phew! I started noticing the exact same problem a couple hours ago and was worried it was related to some new router/firewall settings I had just put in. 

It was a good run with ST, but this might be enough for me to throw in the towel and buy the Aeotec USB z-wave antenna for my Pi. HASS is just so much better at everything I've thrown at it. And much easier to debug- granted I'm no ST expert, but I can't find anything in their logs indicating there's any problem at all right now. 

Please let me know if you manage find a real cause here though!

**Comment by edif30** [comment]
Well count me in, SAME THING HAPPENED TO ME TODAY!  What is going on???? Is this on the ST side?  It's so odd that the MQTT messages get to the hub but then its held for about a minute!  I traced all commands and messages the same as you @jonfink and it doesn't make sense.  I don't see a hub update.  The app has updated but I think a week ago or so.  At first all my devices started acting up and it took a power down for about 15 min for the app to respond like it normally does.  I thought I was out of the woods.  Then everything via HA just takes up to a min or so to go through.  Via the ST app it is instant.  I seriously hope ST didn't just implement some kind of rate limit or filtering.  Because that would be really dumb.  I've been at this for about 4 hours now.

**Comment by edif30** [comment]
How about this WTF news...

https://status.smartthings.com/

**Comment by edif30** [comment]
Another update - my HA commands just started working again instantly.  May be some degradation but at least this is known and I don't have to dick around for an issue that isn't mine! :)

**Comment by jonfink** [comment]
Yeah, my system is back - wish the ST status message from yesterday morning was more clear as to the expected issues:

> Investigating - Some US users may be unable to load the SmartThings app, control devices, or access the web UI. We are currently investigating. 
Jan 4, 07:05 EST

and (finally) updated at 21:00 EST

> Update - Some North American users may continue to experience degraded performance to a full outage which can result in the inability to load the SmartThings mobile app, control devices, or access the web UI. We are continuing to work to address the issue. 
Jan 4, 21:25 EST

Closing this issue as it was never a MQTT Bridge Issue!
